name: Test on Multiple OS

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Operating systems to test
        node-version: [18, 20, 22]                      # Node.js versions to test
        attempt: [1, 2, 3, 4, 5]                        # Repeat tests 5 times

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          npm install cypress --save-dev
          npm install node-xlsx --save-dev
          npm install pg --save-dev
          npm install pdf-parse --save-dev
          npm install @cypress/code-coverage --save-dev
          npx cypress verify

      - name: Start server
        run: |
          npm run start &  # Adjust this if your server is started with a different command
          # Add any necessary command to start your server here

      - name: Wait for the server to be available
        run: |
          if [[ $RUNNER_OS == 'Windows' ]]; then
            # For Windows: Use PowerShell to check if port 8082 is open
            timeout=60  # 60 seconds timeout
            elapsed=0
            while (-not (Test-NetConnection -ComputerName localhost -Port 8082).TcpTestSucceeded -and $elapsed -lt $timeout) {
              Write-Host "Waiting for server..."
              Start-Sleep -Seconds 3
              $elapsed += 3
            }
            if ($elapsed -ge $timeout) {
              Write-Host "Server did not start in time. Failing the test."
              exit 1  # Fail the test if the server is not up within the timeout period
            }
          else
            # For Linux/macOS: Use nc to check if the port is open
            timeout=60  # 60 seconds timeout
            elapsed=0
            while ! nc -z localhost 8082 && [ $elapsed -lt $timeout ]; do
              echo "Waiting for server..."
              sleep 3
              elapsed=$((elapsed + 3))
            done
            if [ $elapsed -ge $timeout ]; then
              echo "Server did not start in time. Failing the test."
              exit 1  # Fail the test if the server is not up within the timeout period
            fi
          fi

      - name: Testing on OS (${{ matrix.os }}) with Node.js (version ${{ matrix.node-version }}) attempt ${{ matrix.attempt }}
        working-directory: ./cypress-tests
        run: |
          echo "Run attempt: ${{ matrix.attempt }}"
          npx cypress run --config-file cypress.config.js


